### ISSUE TITLE
Integration testing against known-good output

### ISSUE THREAD

**Issue by mgmax** [t-oster/LibLaserCut#140]
Currently, it is easy to break some driver without anyone noticing.
We should have a set of input jobs and known (real-world-tested) output files for each driver.
The CI testing should then check that LibLaserCut still produces the same output file. On intentional changes, the set of known-good outputs must be regenerated, and then we know that a specific change should be tested on real machines.

**Comment by t-oster** [comment]
Good idea. I think we should create a unit test which iterates a specific folder which contains those files, maybe in subfolders named like the driver classes

**Comment by t-oster** [comment]
However you would have to do this in visicut since liblasercut doesn't know any input file format

**Comment by mgmax** [comment]
Hm. On the other hand, testing with VisiCut could be quite fragile, as we depend on exactly the same rendering, and we will only notice once the LibLaserCut submodule has been updated.

Testing in LibLaserCut should be possible with LaserScript or just a plain java file such as https://github.com/t-oster/LibLaserCut/blob/d6728e8df802d631fd9f1e54d73fa45a2a26d04b/src/test/java/de/thomas_oster/liblasercut/drivers/LaosCutterTest.java . The only technical requirement would be that the driver supports "write to file". The downside would be that sending the exact test file to the real machine wouldn't be so easy because you'd have to set the IP etc. in the source code.

However, since most (all?) of these bugs were introduced by changes that should not have changed anything in the machine output, I think that a quick-and-dirty test in LibLaserCut would still be a good compromise between development effort and benefit. In the rare case that something changed, then we at least know that testing with VisiCut (or careful analysis of the diff) is required.

**Comment by t-oster** [comment]
We could modify visicut to have an option to write the Laserjob object eg as json to some file, which would be the equivalent of a driver's input file. Then we can create the test jobs easily with visicut and just load the Laserjob object in the unit test

**Comment by t-oster** [comment]
The plain Java way also works but engraving seems to be hard to write, we would need to import some raster image

**Comment by phdoerfler** [comment]
I'll take a crack at this.

**Comment by mgmax** [comment]
@phdoerfler my first attempt I did inbetween can be found in #145. Can certainly be improved.
