### ISSUE TITLE
Enable Codacy for LibLaserCut

### ISSUE THREAD

**Issue by phdoerfler** [t-oster/LibLaserCut#146]
[Codacy](http://codacy.com) is a free (for open source projects like this) webapp that performs static code analysis and tells you how well a project is doing in terms of code quality.

I have it enabled on my forks of LibLaserCut and Visicut and it highlights quite a number of issues worth tackling.

**Comment by mgmax** [comment]
seems done

**Comment by mgmax** [comment]
@t-oster Codacy doesn't seem to be active anymore, at least it doesn't show up in the pull requests, for example #148.

**Comment by t-oster** [comment]
Looks as if the repository has to belong to an organization in order for Codacy to work correctly

**Comment by mgmax** [comment]
But strangely enough it worked some time ago: 
Here it works:
![grafik](https://user-images.githubusercontent.com/1520891/78454390-1a812800-7698-11ea-89b5-36af55f66d68.png)
Here it doesn't show up:
![grafik](https://user-images.githubusercontent.com/1520891/78454439-47353f80-7698-11ea-8d1a-551edb13d7dd.png)

**Comment by phdoerfler** [comment]
Can we also add the Codacy badge to the README? I would have filed a PR but I'm afraid that's something a repo admin has to do.

**Comment by t-oster** [comment]
I added the badges. Not sure if everything works now, but in codacy I can see the commits.
