### ISSUE TITLE
Immidiate start cutting with Epilog Fusion M2

### ISSUE THREAD

**Issue by jophut** [t-oster/LibLaserCut#162]
Hi there,

(I know this is a long-shot but you guys seem to know what you're doing)

I'm looking into LibLaserCut and would like to know if it is compatible with a Epilog Fusion M2 (or can be made?)
This machine has a USB and an network connection.

For me the most important issue is that I need to do a repetitive job (1000+ times) and don't want to start the "RUN" button every time. I already have a tape-feeder which is controlled over an RS232-line. In the past I used a Trotec Speedy machine which supported HPGL, but can't find any support documents for HPGL for a Epilog machine.

Is someone familiar with a Epilog Fusion M2 and knows if the machine supports a "start by command" feature?

**Comment by mgmax** [comment]
See #163 for general compatibility, at least with the previous Fusion model. If Epilog does not offer "start by command" in their driver, I would guess there is no such command.
