### ISSUE TITLE
Execute GCODE VisiCut > Octoprint HTTP Method ?

### ISSUE THREAD

**Issue by LaFabrique35** [t-oster/LibLaserCut#173]
Hello,
I have a laser cutter with a smootieboard driven by Octoprint on RaspberryPi. I would have liked to configure Visicut to use the execute button to automatically send the Gcode to the Octoprint server. Has anyone ever tried ? I stumble on the HTTP protocol which cannot communicate with Octoprint

**Comment by LaFabrique35** [comment]
Hello, I am resuming work on this issue. Thank you for sending the file. I don't quite understand how to use this .jar file? Do I have to integrate it into VisiCut? Unzip it in the VisiCut folders? Thank you for this help

**Comment by t-oster** [comment]
If you use windows, replace it in the program files/visicut folder. If you use OSX, open the .app folder with finder and replace it there

**Comment by LaFabrique35** [comment]
Thank you very much for this work, this new option works wonderfully, it will make my life easier!

**Comment by t-oster** [comment]
Ok, so I will merge this feature into the main version
