### ISSUE TITLE
exportet file for Ruida is named .ruida instead of .rd

### ISSUE THREAD

**Issue by mayermakes** [t-oster/LibLaserCut#183]
for file upload method if you execute a job for a ruida based machine the generated file is called $jobname.ruida
but should be $jobname.rd
renaming the file makes the file readable on the cutter, so it looks like a simple fix.

**Comment by mgmax** [comment]
@kkaempf  can you please have a look?

**Comment by mayermakes** [comment]
the generated file gets copied onto a usb stick and taken to the lasercutter. the ruida controller can only detect/read it if its name $jobname.rd
currently the out put is $jobname.ruida, which can't be processed by the controller.
