### ISSUE TITLE
laser goes straight down in middle of job

### ISSUE THREAD

**Issue by quillford** [t-oster/LibLaserCut#31]
It will be in the middle of a job and then suddenly shoot straight downward then continue back to the job. I haven't looked at the gcode yet. I'll get a video of it up soon and get the gcode. I'm using Marlin on the smoothieboard branch.

**Comment by t-oster** [comment]
are you sure that there is not a "bad pixel" in your drawing? or does it happen on different jobs?

**Comment by mgmax** [comment]
@quillford As the bug seems to be not reproducable, could you please close this bugreport? Thanks.
