### ISSUE TITLE
Provide explicit gcode driver upload method configuration

### ISSUE THREAD

**Issue by pelrun** [t-oster/LibLaserCut#43]
Currently the gcode driver implicitly chooses an upload type (telnet/http/serial, and I just implemented file in #42) depending on which fields are set in the lasercutter config, which is non-obvious. It'd be much better to have an explicit menu choice.

**Comment by madleech** [comment]
That would be good. Currently it can take a little head scratching to, particularly since both url and host are already set to default values when making a new laser cutter.
