### ISSUE TITLE
MakeBlockXYPlotter cannot change Power/Speed during Cut

### ISSUE THREAD

**Issue by t-oster** [t-oster/LibLaserCut#58]
Hi @tur0kk . Some guy wrote me he had problems with the MakeBlockXYPlotter driver in conjunction with LaserScript.
I debugged his problem and found out, you did not preserve the `showPowerAndSpeed` field when cloning the `MakeBlockXYPlotter`. I fixed that in a687ea1. 
While reading your code, I noticed that you power and speed aka delay values are only set in the `toolOn` method.
The problem with that approach is, that there are not necessary `MOVE` commands between `LINE` commands. Meaning one could create a job where the laser head moves with laser on on a specific power and speed and then continues to move but with different speed/power.
In such a job your driver would completely ignore all inbetween changes of power and speed as far as I understand.

**Comment by tur0kk** [comment]
Sorry, I no longer have a MakeBlock plotter and thus can not make any further improvements.
