### ISSUE TITLE
Licensing incompatibility: GPL library present

### ISSUE THREAD

**Issue by pelrun** [t-oster/LibLaserCut#65]
In doing #64 I found the GLPK library used by SCPSolver is purely GPL licensed (which incidentally makes SCPSolver GPL licensed as well.)

This is incompatible with LLC's LGPL license.

Apparently if we switch from GLPK to LSOLVE (http://lpsolve.sourceforge.net/5.5/) then SCPSolver is also LGPL and the problem is resolved, although this requires testing.

**Comment by pelrun** [comment]
This appears to only be used by the TSP optimiser.

**Comment by mgmax** [comment]
Does anyone use the TSP optimizer? As far as I remember it was way too slow, and the "nearest" sorting strategy is good enough for most practical jobs.

I would therefore suggest removing it.

**Comment by pelrun** [comment]
I don't disagree. https://github.com/t-oster/VisiCut/issues/226 essentially ended with the decision to pull it out, but it never happened.

If someone cares enough to make it work properly without the GLPK, then it can always be added back in.

**Comment by pelrun** [comment]
I've added a commit removing the TSP and libraries to my PR now.

**Comment by t-oster** [comment]
should be fixed then....
